apiVersion: v1
kind: Service
metadata:
  name: {{ include "pulp.fullname" . }}-web
  labels:
    {{- include "pulp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.web.service_type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.web.port | default 8080 }}
      targetPort: 8080
      protocol: TCP
      name: web
  selector:
    {{- include "pulp.selectorLabels" . | nindent 4 }}
    tier: web
