apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pulp.fullname" . }}-web
  labels:
    {{- include "pulp.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "pulp.selectorLabels" . | nindent 6 }}
      tier: web
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "pulp.selectorLabels" . | nindent 8 }}
        tier: web
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - image: "{{ .Values.web.image.repository }}:{{ .Values.web.image.tag }}"
          imagePullPolicy: {{ .Values.web.image.pullPolicy }}
          name: {{ include "pulp.fullname" . }}-web
          ports:
            - containerPort: 8080
              name: web
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /etc/opt/rh/rh-nginx116/nginx/nginx.conf
              name: pulp-web-config
              subPath: nginx.conf
      hostname: pulp
      restartPolicy: Always
      volumes:
        - name: pulp-web-config
          configMap:
            name: {{ include "pulp.fullname" . }}-web
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
