apiVersion: v1
kind: Service
metadata:
  name: {{ include "pulp.fullname" . }}-postgres
  labels:
    {{- include "pulp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.postgres.service_type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.postgres.port | default 5432 }}
      targetPort: 5432
      protocol: TCP
      name: pulp-postgres
  selector:
    {{- include "pulp.selectorLabels" . | nindent 4 }}
    tier: postgres
