apiVersion: v1
kind: Service
metadata:
  name: {{ include "pulp.fullname" . }}-content
  labels:
    {{- include "pulp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.content.service_type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.content.port | default 24816 }}
      targetPort: 24816
      protocol: TCP
      name: content
  selector:
    {{- include "pulp.selectorLabels" . | nindent 4 }}
    tier: content
