apiVersion: v1
kind: Service
metadata:
  name: {{ include "pulp.fullname" . }}-api
  labels:
    {{- include "pulp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.api.service_type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.api.port | default 24817 }}
      targetPort: 24817
      protocol: TCP
      name: api
  selector:
    {{- include "pulp.selectorLabels" . | nindent 4 }}
    tier: api
