apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pulp.fullname" . }}-api
data:
  settings.py: |-
{{ .Files.Get "files/settings.py" | indent 4 }}
  database_fields.symmetric.key: |-
{{ .Files.Get "files/database_fields.symmetric.key" | indent 4 }}
