apiVersion: v1
kind: Service
metadata:
  name: {{ include "pulp.fullname" . }}-redis
  labels:
    {{- include "pulp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.redis.service_type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.redis.port | default 6379 }}
      targetPort: 6379
      protocol: TCP
      name: redis
  selector:
    {{- include "pulp.selectorLabels" . | nindent 4 }}
    tier: redis
