kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pulp-data
spec:
  accessModes: [{{ .Values.pulpdata.accessMode | default "ReadWriteMany" | quote }}]
  {{- if .Values.pulpdata.storageClass }}
  {{- if (eq "-" .Values.pulpdata.storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: "{{ .Values.pulpdata.storageClass }}"
  {{- end }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.pulpdata.storage }}
